### PR TITLE
Replace search term validation job

### PR DESCRIPTION
**Pull request by chelseatroy**
The Search Term Data Validation job has been failing for a few months. This job is meant to replace that one, starting fresh from the updated job template. 

I was able to successfully run both of the following commands from the `search_term_data_validation_v2` directory:

- `$pytest`
- `$python search_term_data_validation_v2/main.py --data_validation_origin moz-fx-data-shared-prod.search_terms.sanitization_job_data_validation_metrics --data_validation_reporting_destination mozdata.search_terms_unsanitized_analysis.prototype_data_validation_reports_v1`

I would love for someone to let me know if there is anything else I should be checking here to verify that this container should work!

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is
  referenced, the pull request should include the bug number in the title)
- [ ] Scan the PR and verify that no changes (particularly to
  `.circleci/config.yml`) will cause environment variables (particularly
  credentials) to be exposed in test logs
- [ ] Ensure the container image will be using permissions granted to
  [telemetry-airflow](https://github.com/mozilla/telemetry-airflow/)
  responsibly.

### CODE REVIEW

**Review by quiiver — APPROVED** [review]
lgtm!

**Comment by chelseatroy** [comment]
@quiiver @scholtzan @kik-kik looks like the build is failing here because it thinks my CI config is not up-to-date due to the fact that I removed some optional parameters from the command for running the tests: 

Screenshot 2023-09-05 at 2 53 04 PM

Is there perhaps a way I should be doing this that I didn't do it here?

**Comment by quiiver** [comment]
@chelseatroy i believe you have to regenerate the ci config with the following:

```
./script/update_ci_config
```

**Comment by chelseatroy** [comment]
> @chelseatroy i believe you have to regenerate the ci config with the following:
> 
> ```
> ./script/update_ci_config
> ```

Perfect! Thank you!

**Pull request merged**
