### PR TITLE
fix: set project id

### PR DESCRIPTION
**Pull request by rebecca-burwei**
Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is
  referenced, the pull request should include the bug number in the title)
- [ ] Scan the PR and verify that no changes (particularly to
  `.circleci/config.yml`) will cause environment variables (particularly
  credentials) to be exposed in test logs
- [ ] Ensure the container image will be using permissions granted to
  [telemetry-airflow](https://github.com/mozilla/telemetry-airflow/)
  responsibly.

### CODE REVIEW

**Review by quiiver — APPROVED** [review]

**Review by chelseatroy — APPROVED** [review]
Perfect! Now env vars won't have to set this.

I _wanna_ say that the mozdata project might not allow us to write to the prod table, but I'm not sure of that. @quiiver, is there a data access consideration here for writing the data validation results to production?

**Comment by quiiver** [comment]
@chelseatroy that's a good point. in the DAG we reference the tables via the `moz-fx-data-shared-prod` project prefix. I think we should use that for any ETL work

**Comment by rebecca-burwei** [comment]
I am able to run it with mozdata, but not moz-fx-data-shared-prod where I don't have a create permission.

**Review by chelseatroy — APPROVED** [review]
🎡

**Comment by chelseatroy** [comment]
Merging. Will change projects in a follow on PR!

**Pull request merged**
